name: Java CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --settings maven_settings.xml --file pom.xml clean install -DskipTests=true

      - name: SpotBugs
        run: mvn --batch-mode --settings maven_settings.xml --file pom.xml spotbugs:spotbugs

      - name: PMD
        run: mvn --batch-mode --settings maven_settings.xml --file pom.xml pmd:pmd pmd:cpd

